title: Aurelie Giraud  # your name (or website title) here
logo: "/images/4B67B6D5-984C-45D9-846F-F0E4F3E89F9B.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist | Analytics & Visualization 
  <br><br>
  ğ—¢ğ—» ğ—® ğ—ºğ—¶ğ˜€ğ˜€ğ—¶ğ—¼ğ—» ğ˜ğ—¼ ğ—±ğ—²ğ—ºğ—¼ğ—°ğ—¿ğ—®ğ˜ğ—¶ğ˜‡ğ—² ğ—”ğ—»ğ—®ğ—¹ğ˜†ğ˜ğ—¶ğ—°ğ˜€
  I get the most joy from making real business impact based on data, analytics, and automation. 
  I love to create compelling visualization and aspire to become a Data storyteller as I believe it is essential to share across functions and support the whole organization to thrive. 
  <br><br>
  ğ—œ'ğ—º ğ—® ğ—°ğ˜‚ğ—¿ğ—¶ğ—¼ğ˜‚ğ˜€ ğ—°ğ—®ğ˜!
  Always looking for new opportunities to expand my World, I'm on a journey to find a balance between achievement and fulfillment. This means that I'm continuously researching for improving both my technical and soft skills. As a self-learner, I'd love nothing more than to tackle a business problem - using data gathering, manipulation, visualization, machine learning model development, forecasting, and reporting. Writing articles and blog posts are another way to reinforce my learning process and share my passion. 
  <br><br>
  <a href="https://www.linkedin.com/in/aureliegiraud9000/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
